In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv('/home/perm/sars_escape_netv2/model/M3/greany_preds.csv')

      target  predicted
0        1.0   0.000727
1        1.0   0.002029
2        1.0   0.319785
3        1.0   0.521930
4        1.0   0.998032
...      ...        ...
4609     0.0   0.998874
4610     0.0   0.998874
4611     0.0   0.997719
4612     0.0   0.978397
4613     0.0   0.995473

[4614 rows x 2 columns]

In [28]:
df = df[df['target'] == 1.0] #Get only escape mutants data 
escape_predicted =  df['predicted'].to_numpy()
escape_predicted = escape_predicted[int(escape_predicted.shape[0]/2): -1] #Just get scores for wild only

In [29]:
escape_predicted.shape

(180,)

In [26]:
df1 = pd.read_csv('/home/perm/sars_escape_netv2/data/raw/greaney_fitness_sig.csv')
df1

    mutant           window_seqs  escape_frac
0    E484I  AGSTPCNGVIGFNCYFPLQS       0.3244
1    T376D  VLYNSASFSDFKCYGVSPTK       0.6430
2    T376F  VLYNSASFSFFKCYGVSPTK       0.4903
3    K378L  YNSASFSTFLCYGVSPTKLN       0.4654
4    K378N  YNSASFSTFNCYGVSPTKLN       0.5307
..     ...                   ...          ...
175  S383H  FSTFKCYGVHPTKLNDLCFT       0.4319
176  S383L  FSTFKCYGVLPTKLNDLCFT       0.3650
177  K386D  FKCYGVSPTDLNDLCFTNVY       0.4328
178  N394P  TKLNDLCFTPVYADSFVIRG       0.3204
179  T430Q  YNYKLPDDFQGCVIAWNSNN       0.3006

[180 rows x 3 columns]

In [27]:
escape_fraction = df1['escape_frac'].to_numpy()
escape_fraction.shape

(180,)

In [30]:
corr_mat = np.corrcoef(escape_predicted, escape_fraction)
corr_mat

array([[1.       , 0.0473762],
       [0.0473762, 1.       ]])

In [33]:
correlation_coefficient = corr_mat[0, 1]
correlation_coefficient

0.047376196255506556

In [ ]:
w

In [34]:
correlation_coefficient*100

4.737619625550655